- name: Create Kasten ServiceAccount and Token
  hosts: kasten-lab
  become: yes

  vars:
    sa_name: svc-kasten-local
    namespace: kasten-io
    role_name: svc-kasten-local-admin
    token_duration: 48h
    use_artifact: "{{ use_artifact | default(false) }}"

  tasks:

    - name: Create ServiceAccount
      shell: kubectl -n {{ namespace }} create serviceaccount {{ sa_name }}
      ignore_errors: true

    - name: Create ClusterRoleBinding
      shell: >
        kubectl create clusterrolebinding {{ role_name }}
        --clusterrole=cluster-admin
        --serviceaccount={{ namespace }}:{{ sa_name }}
      ignore_errors: true

    - name: Generate token (long duration)
      shell: >
        kubectl -n {{ namespace }} create token {{ sa_name }} --duration={{ token_duration }}
      register: token_output

    - name: Show credentials
      debug:
        msg:
          - "User: {{ sa_name }}"
          - "Role: cluster-admin"
          - "Token (valid for: {{ token_duration }}) ---> {{ token_output.stdout }} <---"

    - name: Log update (site)
      uri:
        url: "{{ site_webhook_logs }}"
        method: POST
        body_format: json
        body:
          lab_id: "{{ labid }}"
          message: "Service Account, Token and Permissions configured"
        headers:
          Content-Type: "application/json"
          x-webhook-secret: "{{ webhook_secret }}"
        validate_certs: no

    - name: Add Kasten (token) to artifact
      include_role:
        name: artifact
      vars:
        artifact_section:
          kasten:
            token: "{{ token_output.stdout }}"
